/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import datos.RescateDatos;
import modelo.Rescate;
import persistencia.RescatePersistencia;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Osvin
 */

public class VentanaRescates extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRescates.class.getName());

    /**
     * Creates new form VentanaRescates
     */
    
    private RescateDatos datosRescates;
private RescatePersistencia persistencia;
private DefaultTableModel modeloTabla;
    
  public VentanaRescates() {
    initComponents();

    datosRescates = new RescateDatos(100);

    persistencia = new RescatePersistencia("rescates.txt");

    configurarTabla();
    cargarDatos();
    actualizarTabla();
    configurarEventos();

    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbPrioridad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRescates = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Gestión de rescates");

        jLabel2.setText("Código:");

        jLabel3.setText("Especie:");

        txtEspecie.addActionListener(this::txtEspecieActionPerformed);

        jLabel4.setText("Fecha:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Prioridad:");

        cmbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Media", "Alta" }));

        jLabel7.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrado", "En atención", "Completado", "Eliminado" }));

        btnRegistrar.setText("Registrar");

        btnBuscar.setText("Buscar");

        btnCambiarEstado.setText("Cambiar estado");

        btnAtender.setText("Atender");

        btnLimpiar.setText("Limpiar");

        btnRegresar.setText("Regresar");

        tablaRescates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Especie", "Fecha", "Lugar", "Descripción", "Prioridad", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaRescates);

        jLabel8.setText("Ubicación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(txtEspecie))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCambiarEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAtender)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimpiar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegresar)))
                        .addGap(121, 138, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBuscar)
                    .addComponent(btnCambiarEstado)
                    .addComponent(btnAtender)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void configurarTabla() {

    modeloTabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Código",
                "Fecha",
                "Ubicación",
                "Especie",
                "Descripción",
                "Prioridad",
                "Estado"
            }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tablaRescates.setModel(modeloTabla);
}


private void cargarDatos() {

    persistencia.cargar(datosRescates);
}


private void configurarEventos() {

    btnRegistrar.addActionListener(e -> registrarRescate());

    btnBuscar.addActionListener(e -> buscarRescate());

    btnCambiarEstado.addActionListener(e -> cambiarEstadoRescate());

    btnAtender.addActionListener(e -> atenderRescate());

    btnLimpiar.addActionListener(e -> limpiarCampos());

    btnRegresar.addActionListener(e -> {
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
        this.dispose();
    });

    tablaRescates.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {
            cargarRescateSeleccionado();
        }
    });
}


private void registrarRescate() {

    String codigo = txtCodigo.getText().trim();
    String fecha = txtFecha.getText().trim();
    String ubicacion = txtLugar.getText().trim();
    String especie = txtEspecie.getText().trim();
    String descripcion = txtDescripcion.getText().trim();

    String prioridad =
            cmbPrioridad.getSelectedItem().toString();

    String estado =
            cmbEstado.getSelectedItem().toString();


    if (codigo.isEmpty()
            || fecha.isEmpty()
            || ubicacion.isEmpty()
            || especie.isEmpty()
            || descripcion.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Todos los campos son obligatorios."
        );

        return;
    }


    Rescate rescate = new Rescate(
            codigo,
            fecha,
            ubicacion,
            especie,
            descripcion,
            prioridad,
            estado
    );


    if (datosRescates.registrarRescate(rescate)) {

        persistencia.guardar(datosRescates);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Rescate registrado correctamente."
        );

        limpiarCampos();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar el rescate.\n"
                + "Verifica que el código no esté repetido "
                + "y que los datos sean válidos."
        );
    }
}


private void buscarRescate() {

    String codigo = txtCodigo.getText().trim();


    if (codigo.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código del rescate."
        );

        return;
    }


    Rescate rescate =
            datosRescates.buscarRescate(codigo);


    if (rescate == null
            || "Eliminado".equals(rescate.getEstado())) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el rescate."
        );

        return;
    }


    txtCodigo.setText(rescate.getCodigo());

    txtFecha.setText(rescate.getFecha());

    txtLugar.setText(rescate.getUbicacion());

    txtEspecie.setText(rescate.getEspecie());

    txtDescripcion.setText(rescate.getDescripcion());

    cmbPrioridad.setSelectedItem(
            rescate.getPrioridad()
    );

    cmbEstado.setSelectedItem(
            rescate.getEstado()
    );


    seleccionarRescateEnTabla(codigo);
}


private void cambiarEstadoRescate() {

    String codigo = txtCodigo.getText().trim();

    String nuevoEstado =
            cmbEstado.getSelectedItem().toString();


    if (codigo.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código del rescate."
        );

        return;
    }


    Rescate rescate =
            datosRescates.buscarRescate(codigo);


    if (rescate == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el rescate."
        );

        return;
    }


    if (datosRescates.cambiarEstado(
            codigo,
            nuevoEstado)) {

        persistencia.guardar(datosRescates);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Estado cambiado correctamente."
        );

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo cambiar el estado."
        );
    }
}


private void atenderRescate() {

    String codigo = txtCodigo.getText().trim();


    if (codigo.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código del rescate."
        );

        return;
    }


    Rescate rescate =
            datosRescates.buscarRescate(codigo);


    if (rescate == null) {

        JOptionPane.showMessageDialog(
                this,
                "No se encontró el rescate."
        );

        return;
    }


    if (datosRescates.cambiarEstado(
            codigo,
            "Completado")) {

        persistencia.guardar(datosRescates);

        actualizarTabla();

        cmbEstado.setSelectedItem("Completado");

        JOptionPane.showMessageDialog(
                this,
                "Rescate atendido correctamente."
        );

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo atender el rescate."
        );
    }
}


private void limpiarCampos() {

    txtCodigo.setText("");

    txtFecha.setText("");

    txtLugar.setText("");

    txtEspecie.setText("");

    txtDescripcion.setText("");

    cmbPrioridad.setSelectedItem("Media");

    cmbEstado.setSelectedItem("Registrado");

    tablaRescates.clearSelection();
}


private void actualizarTabla() {

    modeloTabla.setRowCount(0);


    for (int i = 0;
            i < datosRescates.getCantidad();
            i++) {

        Rescate rescate =
                datosRescates.getRescate(i);


        if ("Eliminado".equals(rescate.getEstado())) {
            continue;
        }


        modeloTabla.addRow(new Object[]{
            rescate.getCodigo(),
            rescate.getFecha(),
            rescate.getUbicacion(),
            rescate.getEspecie(),
            rescate.getDescripcion(),
            rescate.getPrioridad(),
            rescate.getEstado()
        });
    }
}


private void cargarRescateSeleccionado() {

    int fila =
            tablaRescates.getSelectedRow();


    if (fila == -1) {
        return;
    }


    String codigo =
            tablaRescates.getValueAt(
                    fila,
                    0
            ).toString();


    Rescate rescate =
            datosRescates.buscarRescate(codigo);


    if (rescate == null) {
        return;
    }


    txtCodigo.setText(
            rescate.getCodigo()
    );

    txtFecha.setText(
            rescate.getFecha()
    );

    txtLugar.setText(
            rescate.getUbicacion()
    );

    txtEspecie.setText(
            rescate.getEspecie()
    );

    txtDescripcion.setText(
            rescate.getDescripcion()
    );

    cmbPrioridad.setSelectedItem(
            rescate.getPrioridad()
    );

    cmbEstado.setSelectedItem(
            rescate.getEstado()
    );
}


private void seleccionarRescateEnTabla(String codigo) {

    for (int i = 0;
            i < tablaRescates.getRowCount();
            i++) {

        String codigoTabla =
                tablaRescates.getValueAt(
                        i,
                        0
                ).toString();


        if (codigoTabla.equals(codigo)) {

            tablaRescates.setRowSelectionInterval(
                    i,
                    i
            );

            break;
        }
    }
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaRescates().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRescates;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtLugar;
    // End of variables declaration//GEN-END:variables
}
