/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import datos.SolicitudDatos;
import datos.AnimalDatos;
import datos.AdoptanteDatos;

import modelo.Solicitud;

import persistencia.SolicitudPersistencia;
import persistencia.AnimalPersistencia;
import persistencia.AdoptantePersistencia;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osvin
 */
public class VentanaSolicitudes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaSolicitudes.class.getName());
 private AnimalDatos datosAnimales;
private AdoptanteDatos datosAdoptantes;
private SolicitudDatos datosSolicitudes;
private SolicitudPersistencia persistencia;
private DefaultTableModel modeloTabla;
    /**
     * Creates new form VentanaSolicitudes
     */


   public VentanaSolicitudes() {

    initComponents();

    datosAnimales = new AnimalDatos(100);
    AnimalPersistencia persistenciaAnimales =
            new AnimalPersistencia("animales.txt");
    persistenciaAnimales.cargar(datosAnimales);

    datosAdoptantes = new AdoptanteDatos(100);
    AdoptantePersistencia persistenciaAdoptantes =
            new AdoptantePersistencia("adoptantes.txt");
    persistenciaAdoptantes.cargar(datosAdoptantes);

    datosSolicitudes = new SolicitudDatos(
            100,
            datosAnimales,
            datosAdoptantes
    );

    persistencia =
            new SolicitudPersistencia("solicitudes.txt");

    configurarTabla();

    cargarDatos();

    actualizarTabla();

    configurarEventos();

    setLocationRelativeTo(null);
    
    setDefaultCloseOperation(
    javax.swing.WindowConstants.DISPOSE_ON_CLOSE
);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDpi = new javax.swing.JTextField();
        txtCodigoAnimal = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Gestión de solicitudes");

        jLabel2.setText("Código:");

        jLabel3.setText("DPI adoptante:");

        jLabel4.setText("Código animal:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Aprobada", "Rechazada" }));

        btnRegistrar.setText("Registrar");

        btnBuscar.setText("Buscar");

        btnCambiarEstado.setText("Cambiar Estado");

        btnAtender.setText("Atender");

        btnLimpiar.setText("Limpiar");

        btnRegresar.setText("Regresar");

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "DPI", "Código Animal", "Fecha", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaSolicitudes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarEstado))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(txtDpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnAtender)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCambiarEstado))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void configurarTabla() {

    modeloTabla = new DefaultTableModel(
            new Object[][]{},
            new String[]{
                "Código",
                "DPI Adoptante",
                "Código Animal",
                "Fecha",
                "Estado"
            }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    tablaSolicitudes.setModel(modeloTabla);
}

private void cargarDatos() {
    persistencia.cargar(datosSolicitudes);
}

private void configurarEventos() {

    btnRegistrar.addActionListener(e -> registrarSolicitud());

    btnBuscar.addActionListener(e -> buscarSolicitud());

    btnCambiarEstado.addActionListener(e -> cambiarEstadoSolicitud());

    btnAtender.addActionListener(e -> atenderSolicitud());

    btnLimpiar.addActionListener(e -> limpiarCampos());

    btnRegresar.addActionListener(e -> {
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
        this.dispose();
    });

    tablaSolicitudes.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {
            cargarSolicitudSeleccionada();
        }

    });
}

private void registrarSolicitud() {

    String codigo = txtCodigo.getText().trim();
    String dpi = txtDpi.getText().trim();
    String codigoAnimal = txtCodigoAnimal.getText().trim();
    String fecha = txtFecha.getText().trim();
    String estado = cmbEstado.getSelectedItem().toString();

    if (codigo.isEmpty()
            || dpi.isEmpty()
            || codigoAnimal.isEmpty()
            || fecha.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Todos los campos son obligatorios."
        );
        return;
    }

    Solicitud solicitud = new Solicitud(
            codigo,
            dpi,
            codigoAnimal,
            fecha,
            estado
    );

    if (datosSolicitudes.registrarSolicitud(solicitud)) {

        persistencia.guardar(datosSolicitudes);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Solicitud registrada correctamente."
        );

        limpiarCampos();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo registrar la solicitud.\n"
                + "Verifica que el código no esté repetido,\n"
                + "que el adoptante esté activo y que el animal esté disponible."
        );
    }
}
private void buscarSolicitud() {

    String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código de la solicitud."
        );
        return;
    }

    Solicitud solicitud =
            datosSolicitudes.buscarSolicitud(codigo);

    if (solicitud == null) {
        JOptionPane.showMessageDialog(
                this,
                "No se encontró la solicitud."
        );
        return;
    }

    txtCodigo.setText(solicitud.getCodigo());
    txtDpi.setText(solicitud.getDpiAdoptante());
    txtCodigoAnimal.setText(solicitud.getCodigoAnimal());
    txtFecha.setText(solicitud.getFecha());
    cmbEstado.setSelectedItem(solicitud.getEstado());

    seleccionarSolicitudEnTabla(codigo);
}
private void cambiarEstadoSolicitud() {

    String codigo = txtCodigo.getText().trim();
    String nuevoEstado =
            cmbEstado.getSelectedItem().toString();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código de la solicitud."
        );
        return;
    }

    Solicitud solicitud =
            datosSolicitudes.buscarSolicitud(codigo);

    if (solicitud == null) {
        JOptionPane.showMessageDialog(
                this,
                "No se encontró la solicitud."
        );
        return;
    }

    if (datosSolicitudes.cambiarEstado(
            codigo,
            nuevoEstado)) {

        persistencia.guardar(datosSolicitudes);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Estado cambiado correctamente."
        );

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo cambiar el estado.\n"
                + "Verifica que el animal esté disponible."
        );
    }
}
private void atenderSolicitud() {

    String codigo = txtCodigo.getText().trim();

    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Ingresa el código de la solicitud."
        );
        return;
    }

    Solicitud solicitud =
            datosSolicitudes.buscarSolicitud(codigo);

    if (solicitud == null) {
        JOptionPane.showMessageDialog(
                this,
                "No se encontró la solicitud."
        );
        return;
    }

    String estadoFinal =
            cmbEstado.getSelectedItem().toString();

    if (!"Aprobada".equals(estadoFinal)
            && !"Rechazada".equals(estadoFinal)) {

        JOptionPane.showMessageDialog(
                this,
                "Para atender una solicitud debes seleccionar "
                + "\"Aprobada\" o \"Rechazada\"."
        );
        return;
    }

    if (datosSolicitudes.atenderSolicitud(
            codigo,
            estadoFinal)) {

        persistencia.guardar(datosSolicitudes);

        actualizarTabla();

        JOptionPane.showMessageDialog(
                this,
                "Solicitud atendida correctamente."
        );

        limpiarCampos();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No se pudo atender la solicitud."
        );
    }
}
private void limpiarCampos() {

    txtCodigo.setText("");
    txtDpi.setText("");
    txtCodigoAnimal.setText("");
    txtFecha.setText("");

    cmbEstado.setSelectedItem("Pendiente");

    tablaSolicitudes.clearSelection();
}
private void actualizarTabla() {

    modeloTabla.setRowCount(0);

    for (int i = 0;
            i < datosSolicitudes.getCantidad();
            i++) {

        Solicitud solicitud =
                datosSolicitudes.getSolicitud(i);

        modeloTabla.addRow(new Object[]{
            solicitud.getCodigo(),
            solicitud.getDpiAdoptante(),
            solicitud.getCodigoAnimal(),
            solicitud.getFecha(),
            solicitud.getEstado()
        });
    }
}
private void cargarSolicitudSeleccionada() {

    int fila =
            tablaSolicitudes.getSelectedRow();

    if (fila == -1) {
        return;
    }

    String codigo =
            tablaSolicitudes.getValueAt(fila, 0).toString();

    Solicitud solicitud =
            datosSolicitudes.buscarSolicitud(codigo);

    if (solicitud == null) {
        return;
    }

    txtCodigo.setText(solicitud.getCodigo());
    txtDpi.setText(solicitud.getDpiAdoptante());
    txtCodigoAnimal.setText(solicitud.getCodigoAnimal());
    txtFecha.setText(solicitud.getFecha());
    cmbEstado.setSelectedItem(solicitud.getEstado());
}
private void seleccionarSolicitudEnTabla(String codigo) {

    for (int i = 0;
            i < tablaSolicitudes.getRowCount();
            i++) {

        String codigoTabla =
                tablaSolicitudes.getValueAt(i, 0).toString();

        if (codigoTabla.equals(codigo)) {
            tablaSolicitudes.setRowSelectionInterval(i, i);
            break;
        }
    }
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaSolicitudes().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoAnimal;
    private javax.swing.JTextField txtDpi;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
